### ISSUE TITLE
L1 Mastering Font checklist

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/gideon#2]
### L1 Mastering Font checklist

**Diacritics**
- [x] Inspect the font and choose the best version of the diacritics (in terms of balance, weight, size, contrast) and move them to comb mark.
- [x] Adjust left and right sidebearings of all the comb marks to 0.
- [x] Work on the selected diacritics to ensure the balance among all marks (contrast, weight, size, stroke or others)
- [x] Adjust position, weight, or outlines of the diacritics if needed to, without changing the design of them by using glyphs app locked guidelines.
- [x] Test the comb marks by inspecting all of them in context (right click and choose all glyphs using this component).
- [x] Inspect and balance the below marks (size, weight, balance) e.g. `ogonek` `cedilla` to avoid huge marks
- [x] Delete the legacy marks and add them back so they are made from comb marks.
- [x] Create comb.case marks by making them less tall and less narrow while keeping them at the same weight. (Preferable at the height they are intended to use, to be able to inspect them at their context)
- [x] Create the Vietnamese mark.
- [x] Make component glyphs for all of the font.
- [x] Adjust the anchor position.
- [x] Run the automatic glyphsapp command: update gyph info

**Glyphs & Outlines**
- [x] Create the missing glyphs needed
- [x] Run the automatic glyphsapp command: Add extremes, Correct outlines direction, Remove PS Hint.
- [x] Check kerning and spacing by using the txt files. Fix any kerning and spacing errors if needed for the most common kerning pairs.
- [x] Run the automatic glyphsapp command: `Resolve all metrics` to update the metrics in all the font.
- [x] Check everything once again by going glyph by glyph.
- [x] Run the automatic glyphsapp `Update Glyph Info` command to avoid bad names issues
- [x] Run the automatic glyphsapp `Convert to cubic` command to avoid qcurves

**OT Features**
- [x] Check OpenType features and see if can rename .001 etc... glyphs and generate the automatic OpenType code.
- [x] Check if there is a stylistic set that would correspond to `SmallCaps` feature instead and change it.
- [x] Check if the OpenType code has any error.
- [x] Hit the `compile` button to check everything is working well.

**Testing changes**
- [x] Inspect the font created by the CI GHA to check production errors. If the action isn't included yet in the repo, export and test the font using Glyphs.
- [x] Check the before and after font using `gen-html diff` if needed (for update font cases)
- [x] Check the font on `gen-html proof` to see if it's working well on web. Use the `--imgs` flag to produce images.
- [x] Commit and make PR using images.

**Comment by vv-monsalve** [comment]
Hi @crystaltype, I've performed some fixes needed to the spacing and kerning for Gideon covering the main cases and creating the kerning groups. However, after creating the [Browser Images](https://github.com/googlefonts/gideon/issues/6) there are a lot of undesired 'exceptions' kerning cases that are still causing some spacing issues. E.g. `Sample Text Uppercase` text in the images.

Please take the latest file in repo and make sure that the exception cases are no longer working (yellow ones in the image). I deleted some of them from the Kerning palette, but the actual values remained in the font, so it would need to be a case by case revision.


<img width="1170" alt="Screen Shot 2021-08-11 at 21 31 15" src="https://user-images.githubusercontent.com/48698976/129130534-ebec46c4-e871-4f62-a05f-9174a00128a6.png">

**Comment by crystaltype** [comment]
@vv-monsalve 
Hello Viviana, I've deleted all kerning exception and made a pull request here: https://github.com/googlefonts/gideon/pull/7

**Comment by vv-monsalve** [comment]
Hi @crystaltype, did you apply a script to change the kerning values? After merging the PR with the kerning job on it, there are new kerning pairs that shouldn't be included, e.g. the -19 value between `n n`.

**Before**
<img width="1175" alt="Screen Shot 2021-08-17 at 10 37 00" src="https://user-images.githubusercontent.com/48698976/129779048-2a1dd79f-9573-4802-82ae-95ec6779b7d6.png">

**After**
<img width="1175" alt="Screen Shot 2021-08-17 at 10 36 52" src="https://user-images.githubusercontent.com/48698976/129779080-2636b15c-254c-4b3b-9ad3-b2645a408a20.png">

As mentioned above it required a case by case revision as automatic actions weren't doing the job properly. So for example if `m` has sidebearings arithmetics related to `n` and belong to the same kerning group, there shouldn't be different kerning values for the same letters, e.g. `o n` and `o m`

![Screen Shot 2021-08-17 at 13 18 44](https://user-images.githubusercontent.com/48698976/129779533-a9feb003-ddab-45fa-b5d1-54a2d8fd6cf6.png)


I'll go back to the previous version, make some adjustments and push again the file.
